const {
  fontFamily,
  fontSize,
  lineHeight,
  inset,
  borderWidth,
  flex,
  colors,
  backgroundImage,
} = require("tailwindcss/defaultTheme");

const {
  colors: {
    black,
    white,
    primary,
    gray,
    brown,
    red,
    campaign,
    stars,
    green,
    teal,
    blue,
  },
} = require("./colors.config");

const typographyTheme = require("./typography.config");
/*
 ** TailwindCSS Configuration File
 **
 ** Docs: https://tailwindcss.com/docs/configuration
 ** Default: https://github.com/tailwindcss/tailwindcss/blob/master/stubs/defaultConfig.stub.js
 */
module.exports = {
  variants: {
    margin: ({ after }) => after(["last", "first", "group-hover"]),
    padding: ({ after }) => after(["last", "first", "hover"]),
    width: ({ after }) => after(["hover", "group-hover"]),
    opacity: ({ after }) => after(["group-hover", "disabled"]),
    display: ({ after }) => after(["group-hover"]),
    borderWidth: ({ after }) => after(["last", "first"]),
  },
  theme: {
    screens: {
      xs: "375px",
      sm: "640px",
      md: "768px",
      lg: "801px",
      mxl: "1200px",
      xl: "1440px",
      xxl: "1600px",
    },
    typography: typographyTheme,
    extend: {
      fontFamily: {
        sans: ["HCo Gotham Rounded", ...fontFamily.sans],
        BeyondInfinity: "BeyondInfinity",
        para: ["'Open Sans'", ...fontFamily.sans],
      },
      fontSize: {
        ...fontSize,
        "2xs": ".5rem",
        "10px": "0.625rem",
        "13px": "0.8125rem",
        "18px": "1.125rem",
        "19px": "1.1875rem",
        "1sm": "1.375rem",
        "3xl": "1.625rem",
        "4xl": "2rem",
        "6xl": "3.625rem",
        "7xl": "3.75rem",
        "8xl": "4rem",
        "9xl": "4.5rem",
        20: "5rem",
        24: "6rem",
        26: "8rem",
      },
      letterSpacing: {
        tighter: "-.03em",
        wide: "0.0125em",
        wider: "0.02em",
      },
      lineHeight: {
        ...lineHeight,
        "extra-relaxed": "1.9375rem",
        11: "2.75rem",
        12: "3rem",
        13: "3.25rem",
        15: "3.75rem",
        17: "4.25rem",
        20: "5rem",
        29: "9rem",
      },
      minHeight: {
        12: "3rem",
        13: "3.25rem",
        14: "3.5rem",
        20: "5rem",
        26: "6.5rem",
        28: "7rem",
        42: "10rem",
        44: "11.5rem",
        45: "11.75rem",
        48: "12.5rem",
        64: "16rem",
        70: "17.5rem",
        72: "18rem",
        71: "18.75rem",
        75: "21.875rem",
        78: "23.75rem",
        138: "31.25rem",
        146: "37.5rem",
      },
      maxHeight: {
        12: "3rem",
        13: "3.25rem",
        14: "3.5rem",
        24: "5rem",
        26: "6.5rem",
        28: "7rem",
        34: "8.5rem",
        42: "10rem",
        xxs: "12rem",
        48: "12.5rem",
        49: "13rem",
        50: "14rem",
        64: "16rem",
        70: "17.5rem",
        72: "18rem",
        71: "18.75rem",
        xs: "20rem",
        138: "31.25rem",
        146: "37.5rem",
        initial: "initial",
      },
      minWidth: {
        28: "7rem",
        26: "6.5rem",
        48: "12.5rem",
        74: "19.5rem",
        "1/4": "25%",
        "1/3": "33.333333%",
        "1/2": "50%",
        "3/4": "75%",
        "5/12": "41.666667%",
        "11/12": "90%",
      },
      maxWidth: {
        24: "5rem",
        26: "6.5rem",
        28: "7rem",
        42: "10rem",
        xxs: "12rem",
        70: "17.5rem",
        72: "18rem",
        74: "19.5rem",
        "1/4": "25%",
        "1/3": "33.333333%",
        "1/2": "50%",
        "6/10": "60%",
        "3/4": "75%",
        "5/12": "41.666667%",
        "8/10": "80%",
        "11/12": "90%",
      },
      spacing: {
        0.125: "0.125rem",
        2.5: "0.635rem",
        4.5: "1.125rem",
        7: "1.875rem",
        11: "2.75rem",
        14: "3.5rem",
        18: "4.5rem",
        26: "6.5rem",
        27: "6.75rem",
        30: "7.8125rem",
        33: "8.08375rem",
        34: "8.4375rem",
        36: "8.75rem",
        38: "9.4375rem",
        39: "9.85rem",
        42: "10.3125rem",
        43: "11.125rem",
        44: "11.5rem",
        46: "12rem",
        48: "12.5rem",
        51: "12.75rem",
        52: "13.5rem",
        57: "14.25rem",
        62: "15.5rem",
        63: "15.75rem",
        66: "16.875rem",
        70: "17.5rem",
        71: "18.75rem",
        72: "18rem",
        73: "18.125rem",
        74: "20.188rem",
        75: "22.25rem",
        76: "22.5rem",
        140: "35rem",
        146: "37.5rem",
        78: "23rem",
        79: "24.5rem",
        82: "28rem",
        "1/4": "25%",
        "1/2": "50%",
        full: "100%",
      },
      colors: {
        ...colors,
        primary,
        black,
        white,
        gray,
        brown,
        red: { ...colors.red, ...red },
        campaign,
        stars,
        green: { ...colors.green, ...green },
        teal: { ...colors.teal, ...teal },
        blue,
      },
      inset: {
        ...inset,
        2: "0.5rem",
        4: "1rem",
        "-4": "-1rem",
        7: "1.75rem",
        "-7": "-1.75rem",
        8: "2rem",
        "-8": "-2rem",
        8.5: "2.5rem",
        "-8.5": "-2.5rem",
        9: "2.65rem",
        10: "3rem",
        "-10": "-3rem",
        16: "4rem",
        "-16": "-4rem",
        18: "4.5rem",
        "-18": "-4.5rem",
        20: "5rem",
        28: "7rem",
        56: "14rem",
        "1/4": "25%",
        "-1/4": "-25%",
        "1/2": "50%",
        100: "100%",
        "-100": "-100%",
      },
      borderWidth: {
        ...borderWidth,
        6: "6px",
      },
      flex: {
        ...flex,
        3: "3 3 0%",
        full: "1 0 100%",
        "1/4": "0 0 25%",
      },
      animation: {
        "lds-ring": "lds-ring 1.2s cubic-bezier(0.5, 0, 0.5, 1) infinite",
      },
      keyframes: {
        "lds-ring": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
      },
    },
    backgroundImage: {
      ...backgroundImage,
      "hero-banner": "url('/images/hero_banner_image.jpg')",
    },
  },
  plugins: [
    require("@tailwindcss/typography")({
      modifiers: ["default"],
    }),
    function ({ addBase }) {
      addBase([
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-Light_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-Light_Web.woff2") format("woff2")`,
            fontWeight: "300",
            fontStyle: "normal",
          },
        },
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-LightItalic_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-LightItalic_Web.woff2") format("woff2")`,
            fontWeight: "300",
            fontStyle: "italic",
          },
        },
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-Book_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-Book_Web.woff2") format("woff2")`,
            fontWeight: "400",
            fontStyle: "normal",
          },
        },
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-BookItalic_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-BookItalic_Web.woff2") format("woff2")`,
            fontWeight: "400",
            fontStyle: "italic",
          },
        },
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-Medium_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-Medium_Web.woff2") format("woff2")`,
            fontWeight: "500",
            fontStyle: "normal",
          },
        },
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-MediumItalic_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-MediumItalic_Web.woff2") format("woff2")`,
            fontWeight: "500",
            fontStyle: "italic",
          },
        },
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-Bold_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-Bold_Web.woff2") format("woff2")`,
            fontWeight: "700",
            fontStyle: "normal",
          },
        },
        {
          "@font-face": {
            fontFamily: "HCo Gotham Rounded",
            src: `url("~assets/fonts/GothamRnd-BoldItalic_Web.woff") format("woff"),
                  url("~assets/fonts/GothamRnd-BoldItalic_Web.woff2") format("woff2")`,
            fontWeight: "700",
            fontStyle: "italic",
          },
        },
        {
          "@font-face": {
            fontFamily: "BeyondInfinity",
            fontWeight: "normal",
            fontStyle: "normal",
            fontDisplay: "swap",
            src: `url("~assets/fonts/beyond_infinity-webfont.eot") format("eot"),
            url("~assets/fonts/beyond_infinity-webfont.woff") format("woff"),
            url("~assets/fonts/beyond_infinity-webfont.svg") format("svg"),
            url("~assets/fonts/beyond_infinity-webfont.woff2") format("woff2")`,
          },
        },
      ]);
    },
  ],
  purge: {
    // Learn more on https://tailwindcss.com/docs/controlling-file-size/#removing-unused-css
    enabled: process.env.NODE_ENV === "production",
    content: [
      "components/**/*.vue",
      "slices/**/*.vue",
      "layouts/**/*.vue",
      "pages/**/*.vue",
      "plugins/**/*.js",
      "nuxt.config.js",
    ],
    options: {
      whitelist: ["bg-red-800"],
    },
  },
};
