#import "~/gql/fragments/Shopify.gql"

# SEE https://help.shopify.com/en/api/storefront-api/reference/interface/node
query CheckoutById($checkoutId: ID!) {
  node(id: $checkoutId) {
    __typename
    ...CheckoutFragment
  }
}
